/**
 * Universal ATS Field Registry
 * Reverse-Engineered Metadata Registry for US Application Forms
 * File: backend/src/config/universalFieldRegistry.js
 */

const UNIVERSAL_FIELD_REGISTRY = [
  // SECTION 1: CORE IDENTITY
  {
    canonicalId: 'identity.firstName',
    displayName: 'First Name',
    description: 'Legal given name',
    section: 'identity',
    subsection: 'basic',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: true, pattern: '^[A-Za-z\\s\'-]{1,50}$' },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 100,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: true,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'Jane',
    aliases: ['first_name', 'given_name', 'legal_first_name', 'fname', 'first']
  },
  {
    canonicalId: 'identity.middleName',
    displayName: 'Middle Name',
    description: 'Middle or second given name',
    section: 'identity',
    subsection: 'basic',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 60,
    atsPlatforms: ['Workday', 'Taleo', 'iCIMS', 'Oracle', 'USAJobs'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'Marie',
    aliases: ['middle_name', 'middle_initial']
  },
  {
    canonicalId: 'identity.lastName',
    displayName: 'Last Name',
    description: 'Legal family name',
    section: 'identity',
    subsection: 'basic',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: true, pattern: '^[A-Za-z\\s\'-]{1,50}$' },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 100,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: true,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'Doe',
    aliases: ['last_name', 'family_name', 'surname', 'lname', 'last']
  },
  {
    canonicalId: 'identity.preferredName',
    displayName: 'Preferred Name / Nickname',
    description: 'Chosen or preferred name for communications',
    section: 'identity',
    subsection: 'basic',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 75,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'Alex',
    aliases: ['preferred_name', 'nickname', 'chosen_name']
  },
  {
    canonicalId: 'identity.pronouns',
    displayName: 'Preferred Pronouns',
    description: 'Gender pronouns (e.g. She/Her, They/Them)',
    section: 'identity',
    subsection: 'basic',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 65,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: false,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'They/Them',
    aliases: ['pronouns', 'preferred_pronouns']
  },

  // SECTION 2: CONTACT INFORMATION
  {
    canonicalId: 'contact.email',
    displayName: 'Primary Email Address',
    description: 'Primary contact email address',
    section: 'contact',
    subsection: 'primary',
    inputType: 'email',
    dataType: 'string',
    validationRules: { required: true, pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$' },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 100,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: false,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: true,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'jane.doe@example.com',
    aliases: ['email', 'email_address', 'primary_email', 'applicantEmail']
  },
  {
    canonicalId: 'contact.phone',
    displayName: 'Phone Number',
    description: 'Primary mobile or phone number',
    section: 'contact',
    subsection: 'primary',
    inputType: 'tel',
    dataType: 'string',
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 100,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: false,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: '+1 (555) 019-2831',
    aliases: ['phone', 'mobile', 'cell', 'phoneNumber', 'telephone']
  },

  // SECTION 3: LOCATION
  {
    canonicalId: 'location.country',
    displayName: 'Country of Residence',
    description: 'Primary country of residence',
    section: 'location',
    subsection: 'address',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 98,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'United States',
    aliases: ['country', 'residence_country', 'nation']
  },
  {
    canonicalId: 'location.state',
    displayName: 'State / Province',
    description: 'State or territory',
    section: 'location',
    subsection: 'address',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 98,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'California',
    aliases: ['state', 'province', 'region', 'address_state']
  },
  {
    canonicalId: 'location.city',
    displayName: 'City',
    description: 'City of residence',
    section: 'location',
    subsection: 'address',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 98,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'San Francisco',
    aliases: ['city', 'town', 'municipality', 'address_city']
  },
  {
    canonicalId: 'location.zipCode',
    displayName: 'Zip / Postal Code',
    description: 'Postal or Zip code',
    section: 'location',
    subsection: 'address',
    inputType: 'text',
    dataType: 'string',
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 95,
    atsPlatforms: ['Workday', 'iCIMS', 'Taleo', 'Oracle', 'SmartRecruiters'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: '94107',
    aliases: ['zip', 'zip_code', 'postal_code', 'postcode']
  },

  // SECTION 4: WORK AUTHORIZATION & COMPLIANCE
  {
    canonicalId: 'authorization.isAuthorizedInUS',
    displayName: 'US Work Authorization Status',
    description: 'Are you legally authorized to work in the United States?',
    section: 'authorization',
    subsection: 'us_legal',
    inputType: 'select',
    dataType: 'boolean',
    options: [
      { label: 'Yes - Legally Authorized', value: true },
      { label: 'No - Not Authorized', value: false }
    ],
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 96,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: true,
    aliases: ['authorized_to_work', 'work_authorization', 'legal_right_to_work']
  },
  {
    canonicalId: 'authorization.requiresSponsorshipNowOrFuture',
    displayName: 'Visa Sponsorship Requirement',
    description: 'Will you now or in the future require visa sponsorship for employment?',
    section: 'authorization',
    subsection: 'us_legal',
    inputType: 'select',
    dataType: 'boolean',
    options: [
      { label: 'No - Sponsorship Not Required', value: false },
      { label: 'Yes - Sponsorship Required', value: true }
    ],
    validationRules: { required: true },
    isRequired: true,
    isConditional: false,
    frequencyPercent: 95,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: false,
    aliases: ['visa_sponsorship', 'require_sponsorship', 'future_sponsorship']
  },
  {
    canonicalId: 'compliance.isITARUSPerson',
    displayName: 'US ITAR / EAR Export Control Status',
    description: 'Are you a US Citizen, Permanent Resident (Green Card holder), or Protected Individual under ITAR/EAR?',
    section: 'authorization',
    subsection: 'defense_compliance',
    inputType: 'select',
    dataType: 'boolean',
    options: [
      { label: 'Yes - US Person under ITAR/EAR', value: true },
      { label: 'No - Non-US Person', value: false }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 45,
    atsPlatforms: ['Greenhouse', 'Lever', 'Workday', 'iCIMS'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: true,
    shouldBeAdvanced: true,
    exampleValue: true,
    aliases: ['itar_status', 'export_control', 'us_person_itar']
  },
  {
    canonicalId: 'compliance.securityClearance',
    displayName: 'US Security Clearance Level',
    description: 'Active US Government Security Clearance Level',
    section: 'authorization',
    subsection: 'defense_compliance',
    inputType: 'select',
    dataType: 'string',
    options: [
      { label: 'None', value: 'None' },
      { label: 'Confidential', value: 'Confidential' },
      { label: 'Secret', value: 'Secret' },
      { label: 'Top Secret', value: 'Top Secret' },
      { label: 'Top Secret / SCI (TS/SCI)', value: 'TS/SCI' }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 42,
    atsPlatforms: ['Workday', 'Oracle', 'iCIMS', 'USAJobs'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: true,
    shouldBeAdvanced: true,
    exampleValue: 'None',
    aliases: ['security_clearance', 'clearance_level']
  },

  // SECTION 5: PROFILES & SOCIAL LINKS
  {
    canonicalId: 'links.linkedin',
    displayName: 'LinkedIn Profile URL',
    description: 'Link to your primary LinkedIn profile',
    section: 'links',
    subsection: 'social',
    inputType: 'url',
    dataType: 'string',
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 94,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'https://linkedin.com/in/janedoe',
    aliases: ['linkedin', 'linkedin_url', 'social_linkedin']
  },
  {
    canonicalId: 'links.github',
    displayName: 'GitHub Profile URL',
    description: 'Link to your GitHub profile or organization',
    section: 'links',
    subsection: 'social',
    inputType: 'url',
    dataType: 'string',
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 82,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: false,
    gitHubParsable: true,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'https://github.com/janedoe',
    aliases: ['github', 'github_url', 'github_profile']
  },
  {
    canonicalId: 'links.portfolio',
    displayName: 'Portfolio / Personal Website URL',
    description: 'Link to your personal website or portfolio',
    section: 'links',
    subsection: 'social',
    inputType: 'url',
    dataType: 'string',
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 78,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'SmartRecruiters'],
    aiFillable: true,
    resumeParsable: true,
    linkedInParsable: true,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 'https://janedoe.dev',
    aliases: ['portfolio', 'website', 'personal_website', 'personal_site']
  },

  // SECTION 6: TARGET PREFERENCES & COMPENSATION
  {
    canonicalId: 'preferences.desiredMinSalary',
    displayName: 'Desired Annual Base Salary ($ USD)',
    description: 'Minimum target annual compensation in USD',
    section: 'preferences',
    subsection: 'compensation',
    inputType: 'number',
    dataType: 'number',
    validationRules: { required: false, min: 0 },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 75,
    atsPlatforms: ['Workday', 'SmartRecruiters', 'Taleo', 'Oracle', 'iCIMS'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: 140000,
    aliases: ['desired_salary', 'expected_salary', 'compensation_target']
  },
  {
    canonicalId: 'preferences.noticePeriod',
    displayName: 'Notice Period / Earliest Start Date',
    description: 'Your availability to begin a new role',
    section: 'preferences',
    subsection: 'availability',
    inputType: 'select',
    dataType: 'string',
    options: [
      { label: 'Immediate / Ready Now', value: 'Immediate' },
      { label: '2 Weeks Notice', value: '2 Weeks' },
      { label: '1 Month Notice', value: '1 Month' },
      { label: 'More than 1 Month', value: '1+ Month' }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 72,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: '2 Weeks',
    aliases: ['notice_period', 'earliest_start_date', 'availability']
  },
  {
    canonicalId: 'preferences.willingToRelocate',
    displayName: 'Willingness to Relocate',
    description: 'Are you open to relocating for the right opportunity?',
    section: 'preferences',
    subsection: 'mobility',
    inputType: 'select',
    dataType: 'boolean',
    options: [
      { label: 'Yes - Willing to Relocate', value: true },
      { label: 'No - Local / Remote Only', value: false }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 68,
    atsPlatforms: ['Workday', 'SmartRecruiters', 'Taleo', 'Oracle', 'iCIMS'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: true,
    isSensitive: false,
    shouldBeAdvanced: false,
    exampleValue: false,
    aliases: ['relocation', 'willing_to_relocate', 'relocate']
  },

  // SECTION 7: US EEO DEMOGRAPHICS
  {
    canonicalId: 'demographics.gender',
    displayName: 'Gender Identity (US EEO)',
    description: 'Equal Employment Opportunity Gender Self-Identification',
    section: 'demographics',
    subsection: 'eeo',
    inputType: 'select',
    dataType: 'string',
    options: [
      { label: 'Male', value: 'Male' },
      { label: 'Female', value: 'Female' },
      { label: 'Non-Binary / Gender Diverse', value: 'Non-Binary' },
      { label: 'Decline to Disclose', value: 'Decline' }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 88,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: false,
    isSensitive: true,
    shouldBeAdvanced: false,
    exampleValue: 'Decline',
    aliases: ['eeo_gender', 'gender_identity', 'sex']
  },
  {
    canonicalId: 'demographics.raceEthnicity',
    displayName: 'Race / Ethnicity (US EEO)',
    description: 'Equal Employment Opportunity Race & Ethnicity Self-Identification',
    section: 'demographics',
    subsection: 'eeo',
    inputType: 'select',
    dataType: 'string',
    options: [
      { label: 'American Indian or Alaska Native', value: 'American Indian' },
      { label: 'Asian', value: 'Asian' },
      { label: 'Black or African American', value: 'Black' },
      { label: 'Hispanic or Latino', value: 'Hispanic' },
      { label: 'Native Hawaiian or Other Pacific Islander', value: 'Pacific Islander' },
      { label: 'White', value: 'White' },
      { label: 'Two or More Races', value: 'Two or More' },
      { label: 'Decline to Disclose', value: 'Decline' }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 88,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: false,
    isSensitive: true,
    shouldBeAdvanced: false,
    exampleValue: 'Decline',
    aliases: ['eeo_race', 'race_ethnicity', 'race']
  },
  {
    canonicalId: 'demographics.veteranStatus',
    displayName: 'Veteran Status (US VEVRAA)',
    description: 'Protected Veteran Self-Identification under VEVRAA',
    section: 'demographics',
    subsection: 'eeo',
    inputType: 'select',
    dataType: 'string',
    options: [
      { label: 'I am a protected veteran', value: 'Veteran' },
      { label: 'I am not a protected veteran', value: 'NotVeteran' },
      { label: 'Decline to Disclose', value: 'Decline' }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 88,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: false,
    isSensitive: true,
    shouldBeAdvanced: false,
    exampleValue: 'Decline',
    aliases: ['eeo_veteran', 'veteran_status', 'vevraa']
  },
  {
    canonicalId: 'demographics.disabilityStatus',
    displayName: 'Disability Status (US Form CC-305)',
    description: 'Voluntary Self-Identification of Disability under Form CC-305',
    section: 'demographics',
    subsection: 'eeo',
    inputType: 'select',
    dataType: 'string',
    options: [
      { label: 'Yes, I have a disability or previously had a disability', value: 'Yes' },
      { label: 'No, I do not have a disability', value: 'No' },
      { label: 'Decline to Disclose', value: 'Decline' }
    ],
    validationRules: { required: false },
    isRequired: false,
    isConditional: false,
    frequencyPercent: 88,
    atsPlatforms: ['Greenhouse', 'Lever', 'Ashby', 'Workday', 'SmartRecruiters', 'iCIMS', 'Taleo', 'Oracle'],
    aiFillable: true,
    resumeParsable: false,
    linkedInParsable: false,
    gitHubParsable: false,
    canBeInferred: false,
    isSensitive: true,
    shouldBeAdvanced: false,
    exampleValue: 'Decline',
    aliases: ['eeo_disability', 'disability_status', 'form_cc305']
  }
];

module.exports = UNIVERSAL_FIELD_REGISTRY;
